# https://github.com/drajver5siti/PHPUnit/settings/actions, grant GITHUB_TOKEN write access 
on:
    workflow_dispatch:
        inputs:
            tag_name:
                description: 'Tag name for the release'
                required: true
    # push:
    #     tags:
    #         - 'v*'

jobs:
    run_tests:
        name: Run Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
                # extensions:

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist
            
            - name: Run tests
              run: |
                export TERM=xterm
                composer test

    publish_release:
        name: Publish Release
        needs: run_tests
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.WORKFLOWS_BOT_PAT }}

            - name: Create the new tag
              run: |
                git config user.name "drajver5siti"
                git config user.email "drajver5siti@users.noreply.github.com"
                git tag ${{ github.event.inputs.tag_name }}
                git push --tags

            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create the release
              uses: actions/create-release@v1
              with:
                tag_name: ${{ github.event.inputs.tag_name }}
                release_name: Release ${{ github.event.inputs.tag_name }}
                body: |
                    This release was generated automatically
                draft: false
                prerelease: false

              env:
                # GITHUB_TOKEN: ${{ secrets.WORKFLOWS_BOT_PAT }} 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
