on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    run_tests:
        name: Run Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.1'
                # extensions:

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --no-scripts
            
            - name: Run tests
              run: composer test

    publish_release:
        name: Publish Release
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Create the release
              uses: actions/create-release@v1
              with:
                tag_name: ${{ github.ref_name }}
                release_name: Release ${{ github.ref_name }}
                body: |
                    This release was generated automatically
                draft: false
                prerelase: false

              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
